# Generated by Django 5.2.15 on 2026-07-12 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=50, unique=True)),
                ('operator', models.CharField(choices=[('gt', 'Greater than'), ('lt', 'Less than'), ('outside_range', 'Outside range (below value or above value_high)')], max_length=20)),
                ('value', models.FloatField()),
                ('value_high', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLMFailureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('triage', 'Triage'), ('retry', 'Retry Triage'), ('health_tip', 'Health Tip')], max_length=20)),
                ('error_type', models.CharField(max_length=100)),
                ('error_message', models.TextField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('health_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_failures', to='health_records.healthrecord')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
