# Generated by Django 5.2.15 on 2026-06-08 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triage_level', models.CharField(choices=[('see_doctor', 'See Doctor'), ('visit_pharmacy', 'Visit Pharmacy'), ('rest_at_home', 'Rest at Home')], max_length=20)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('confidence_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('hard_rule_triggered', models.BooleanField(default=False)),
                ('hard_rule_metric', models.CharField(blank=True, max_length=50, null=True)),
                ('recommendation_text', models.TextField()),
                ('follow_up_flag', models.BooleanField(default=False)),
                ('follow_up_hours', models.IntegerField(blank=True, null=True)),
                ('llm_model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('prompt_sent', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('health_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage_result', to='health_records.healthrecord')),
            ],
        ),
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readings_summary', models.JSONField()),
                ('disclaimer_text', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('health_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='health_records.healthrecord')),
                ('triage_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='reports.triageresult')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
